modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="All rights reserved"

[[mods]]
modId="artificersexpansion" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory

displayName="Artificer's Expansion" #mandatory

logoFile="logo.png" #optional

credits="Thanks to the wonderful devs of Create and Mana & Artifice" #optional

authors="Rowan The Modder" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
An addon mod for Mana & Artifice and Create, transforming Create into an addon for Mana & Artifice.
'''

[[dependencies.artificersexpansion]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="mna"
    mandatory=true
    versionRange="[1.7.1.20,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="create"
    mandatory=true
    versionRange="[v0.4f,)"
    ordering="BEFORE"
    side="BOTH"