modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="artificersexpansion"

version="${file.jarVersion}"

displayName="Artificer's Expansion"

logoFile="logo.png"

credits="Thanks to the wonderful devs of Create and Mana & Artifice"

authors="Rowan The Modder"

description='''
An addon mod for Mana & Artifice and Create, transforming Create into an addon for Mana & Artifice.
'''

[[dependencies.artificersexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="mna"
    mandatory=true
    versionRange="[1.7.2.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.artificersexpansion]]
    modId="create"
    mandatory=true
    versionRange="[v0.5.0,)"
    ordering="BEFORE"
    side="BOTH"